name: Test release

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get the changelog
        id: get_changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        run: |
          . .github/workflows/release_info.sh
          echo ::set-output name=NEW_TAG::${NEW_TAG}
          echo ::set-output name=CHANGELOG::${CHANGELOG}
          echo ::set-output name=SKIP_RELEASE::${SKIP_RELEASE}
      - name: Create release
        if: steps.get_changelog.outputs.SKIP_RELEASE == 'false'
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
           tag_name: ${{ steps.get_changelog.outputs.NEW_TAG  }}
           release_name: spinnaker-event-parser ${{ steps.get_changelog.outputs.NEW_TAG }}
           body: |
             ${{ steps.get_changelog.outputs.CHANGELOG }}
           draft: false
           prerelease: false