name: Test release

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get the changelog
        id: get_changelog
        run: |
          export PREVIOUS_RELEASE_TAG=`curl --silent "https://api.github.com/repos/jonsie/spinnaker-event-parser/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'`
          export COMMITS=`git log ${GITHUB_REF/refs\/tags\//}...$PREVIOUS_RELEASE_TAG --pretty=format:"%s"`
          echo ::set-output name=CHANGELOG::${COMMITS}
      - name: Create release
        id: create_release
        uses: actions/create-release@1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
           tag_name: ${{ github.ref }}
           release_name: spinnaker-event-parser ${{ github.ref }}
           body: |
             ${{ steps.get_changelog.outputs.CHANGELOG }}
           draft: false
           prerelease: false