name: Test release

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get the changelog
        id: get_changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        run: |
          export PREVIOUS_RELEASE_TAG=`curl --silent "https://api.github.com/repos/jonsie/${{ github.event.repository.name }}/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'`
          export THIS_TAG=${GITHUB_REF/refs\/tags\//}
          export CHANGELOG=`git log $THIS_TAG..$PREVIOUS_RELEASE_TAG --pretty=format:"%s"`
          export SKIP_RELEASE=`[[ "$PREVIOUS_RELEASE_TAG" = "$THIS_TAG" ]] && echo "true" || echo "false"`
          echo ::set-output name=CHANGELOG::${CHANGELOG}
          echo ::set-output name=SKIP_RELEASE::${SKIP_RELEASE}
      - name: Create release
        if: steps.get_changelog.outputs.SKIP_RELEASE == 'false'
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
           tag_name: ${{ github.ref }}
           release_name: spinnaker-event-parser ${{ github.ref }}
           body: |
             ${{ steps.get_changelog.outputs.CHANGELOG }}
           draft: false
           prerelease: false