name: Release

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
    - "v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Get the changelog
        id: get_changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        run: |
          . .github/workflows/release_info.sh ${{ github.event.repository.name }}
          echo ::set-output name=CHANGELOG::$(echo -e "${CHANGELOG}")
          echo ::set-output name=SKIP_RELEASE::${SKIP_RELEASE}
      - name: Create release
        if: steps.get_changelog.outputs.SKIP_RELEASE == 'false' && github.event.ref == 'v[0-9]+.[0-9]+.[0-9]+'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
           tag_name: ${{ github.ref }}
           release_name: ${{ github.event.repository.name }} ${{ github.ref }}
           body: |
            ${{ steps.get_changelog.outputs.CHANGELOG }}
           draft: false
           prerelease: false
      - name: Create prerelease
        if: steps.get_changelog.outputs.SKIP_RELEASE == 'false' && github.event.ref == 'v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        with:
           tag_name: ${{ github.ref }}
           release_name: ${{ github.event.repository.name }} ${{ github.ref }}
           body: |
            ${{ steps.get_changelog.outputs.CHANGELOG }}
           draft: false
           prerelease: true